version:  '3.2'
services:
  zookeeper:
    image: "confluent/zookeeper"
    networks:
      - spring
    ports:
      - 2181:2181

  kafka:
    image: "confluent/kafka"
    networks:
      - spring
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper

networks:
  spring: